### PR TITLE
Clean up utils

### PR DESCRIPTION
**Pull request by andLaing**
Starts the refactoring of the utils.jl functions

### CODE REVIEW

**Comment by jjgomezcadenas** [comment]
There is a problem. I cannot follow the links  to see what you have done, when I click I end up in a wrong page. Can you fix it? Perhaps re-send PR?

**Comment by jjgomezcadenas** [comment]
For instance, clicking in your first commit, send me to:

**Comment by jjgomezcadenas** [comment]
https://github.com/andLaing/ATools/issues/10

**Comment by jjgomezcadenas** [comment]
Which doesn't make any sense...

**Comment by andLaing** [comment]
It's weird, everything's public but it seems to think the commits aren't.

I tried force pushing to no effect so I think I'll close and try to resubmit.

**Pull request closed without merging**
