### PR TITLE
Function tidy

### PR DESCRIPTION
**Pull request by andLaing**
General tidy of the ATools functions.

### CODE REVIEW

**Comment by andLaing** [comment]
I think we need to add a couple of variables to the reduced data parameter set too. There seem to be some cases where we need the true interaction time saved. Here or another PR? It will affect some tests etc

**Comment by jjgomezcadenas** [comment]
Another PR

**Review by jjgomezcadenas — COMMENTED** [review]
Below an example of a function that uses pretty smart functionality from data frames. All very nice, but function could use a few comments. For example a line explaing what "displacement" do, and such. These functional programming style is very nice and concise, but tends to be hard to read unless one helps with comments. 

function time_of_flight(df::DataFrame, source_xyz::Vector{Symbol},
        int_xyz::Vector{Symbol}, n::Real=1.0)
    function displacement(x1, y1, z1, x2, y2, z2)
        norm.(eachrow(hcat(x1, y1, z1) - hcat(x2, y2, z2)))
    end
    cc       = SpeedOfLightInVacuum / n
   
    path_len = combine(df, vcat(int_xyz, source_xyz) => displacement => :path)
    return uconvert.(ps, path_len[!, :path] ./ cc)
end

**Review by jjgomezcadenas — COMMENTED** [review]
Another example, pretty function that could use a couple of extra comments:

function mean_std(x::Vector{T}, xmin::T=typemin(T), xmax::T=typemax(T);
	              w::Union{Nothing, Vector{T}}=nothing) where T
	mask = broadcast(range_bound(xmin, xmax, ATools.OpenBound), x)
    xx   = x[mask]
	if isnothing(w)
		ww = ones(eltype(xx), length(xx))
	else
		ww = w[mask]
	end
    return mean_and_std(xx, FrequencyWeights(ww), corrected=true)
end

**Comment by jjgomezcadenas** [comment]
In general I like very much the work done here. In particular all the important part of histos, fits and such was developed in a rush and was terrible programming. I am approving and merging the PR as it is, but here a few suggestions:

1. Add more comments when you use advanced functional programming techniques or advanced dataframe functions, so that the reader gets a hint o what the function does.
2. Try to make the doctring good enough to be used for automatic doc.
3. Try and generate the docs for the functions, this will tell us if the doc is good enough.
4. In addition of tests, histogram and fitting functions could benefit from having a "example notebook" where they are illsutrated. This could also be very useful for the course.

Good job!

**Comment by andLaing** [comment]
> In general I like very much the work done here. In particular all the important part of histos, fits and such was developed in a rush and was terrible programming. I am approving and merging the PR as it is, but here a few suggestions:
> 
>     1. Add more comments when you use advanced functional programming techniques or advanced dataframe functions, so that the reader gets a hint o what the function does.
> 
>     2. Try to make the doctring good enough to be used for automatic doc.
> 
>     3. Try and generate the docs for the functions, this will tell us if the doc is good enough.
> 
>     4. In addition of tests, histogram and fitting functions could benefit from having a "example notebook" where they are illsutrated. This could also be very useful for the course.
> 
> 
> Good job!

I haven't used the automatic docs before, basically I've just been following what was there. I'll look into improvements for the next updates.

**Pull request merged**
