### PR TITLE
Scatter lors

### PR DESCRIPTION
**Pull request by andLaing**
Implements the new parameters necessary to save energy information for LORs.

### CODE REVIEW

**Comment by andLaing** [comment]
First PR, @jjgomezcadenas @jacg

**Comment by jjgomezcadenas** [comment]
Tests are failing....

**Comment by jjgomezcadenas** [comment]
All checks now work. It is ready to be approved it you are done

**Comment by andLaing** [comment]
Think that's everything in ATools for the jobs we wanted to launch.

**Comment by jjgomezcadenas** [comment]
Merged!

**Pull request merged**
